server:
  port: 8084
spring:
  application:
    name: attender-service

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create


  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: host

yoke:
  notify:
    url: http://localhost:8082/event