server:
  port: 8084
spring:
  application:
    name: attender-service

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create


  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: {cipher}8beb9bc717618d630e23c9cc6b71feaee695603027882fda60cee1e248c6676c

yoke:
  notify:
    url: http://localhost:8082/event